### ISSUE TITLE
训练的完整步骤

### ISSUE THREAD

**Issue by yitan800** [ssbuild/t5_finetuning#12]
能不能在README里更新一下训练的完整步骤？另外也说明一下是否一定需要GPU? 谢谢

**Comment by ssbuild** [comment]
下载预训练权重，修改相应配置，制作数据，训练就行了， 需要gpu.

**Comment by yitan800** [comment]
请问训练一定需要GPU 吗？没有就没法训练吗？目前使用chatyuan-large-v2倒是可以不用GPU

**Comment by ssbuild** [comment]
cpu训练没有意义， 差太多
