### ISSUE TITLE
训练loss不降

### ISSUE THREAD

**Issue by yc930401** [ssbuild/t5_finetuning#6]
42万条医学问答数据。刚训练第一个epoch，训练进度只有5%、训练了1000+个batch，loss就开始反弹。chatglm的旧版代码也是同样，loss很快会反弹，新版代码就ok了。是不是chatyuan也是类似？有点儿小bug还没修改~麻烦大神看一下呗

**Comment by ssbuild** [comment]
不应该吧，这个模型很成熟，而且开源彻底，不像之前的chatglm 半开源。
能上传下你的配置文件吗

**Comment by yc930401** [comment]
应该是lr太大了..减小应该ok
